### ISSUE TITLE
Demo needs Mysql but should be 'standalone'

### ISSUE THREAD

**Issue by michaldo** [la-team/lightadmin-demo#2]
According to https://github.com/la-team/light-admin, "By default, the app will run in 'embedded' mode which does not require any external setup"

But I get Mysql error when I run demo: "com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure"

Please restore option to boot demo without any setup (as it was in past I think) or give instruction for required setup

**Comment by lazaridis-com** [comment]
@michaldo , check the latest https://github.com/la-team/light-admin code, it includes the spring-boot example again.

**Comment by michaldo** [comment]
OK. Now is clear how to run demo
